name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64]
        compiler: [gcc, clang]
    env:
      ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v3
    - uses: jirutka/setup-alpine@v1
    - name: Prepare build environment
      run: ./.ci-prepare.sh ${{ matrix.compiler }}
      shell: alpine.sh --root {0}
    - name: Build
      run: ./.ci-build.sh
      shell: alpine.sh {0}
    - name: 查找镜像位置 (Debug)
      run: find . -name "Image*" && find . -name "*.dtb"
      shell: alpine.sh {0}
    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ matrix.arch }}-${{ matrix.compiler }}
        path: |
          **/arch/${{ matrix.arch }}/boot/Image*
          **/arch/${{ matrix.arch }}/boot/dts/qcom/*.dtb
